### ISSUE TITLE
Minha contribuição :)

### ISSUE THREAD

**Issue by willianwelbert** [vinirossi/vinirossi.github.io#3]
Contribuo contigo dando uma revisadinha no inglês da  página, segue alterado:

Sempre que rola um **@**lugar/empresa, lê-se esse arroba como "at" que é como nós dizermos "em/na/no".
Então no primeiro caso mudei pra" Estagiario na valledevs" ou "Intern @valledevs".
Nas outras linhas só alterei a conjugação/ordem das coisas pra ficar mais claro.

Espero que goste e desculpa a intromissão rs

<p class="description">Intern <a href="https://twitter.com/valledevs" target="_blank">@valledevs</a> &nbsp;&bull;&nbsp; Systems for Internet student &nbsp;&bull;&nbsp; Meetup organizer <a href="https://twitter.com/meetuphtmlsp" target="_blank">@meetuphtmlsp</a></p>

Abraços!

**Comment by vinirossi** [comment]
Muito obrigado @willianwelbert pela contribuição e pela explicação. Já fiz as alterações. Qualquer outro feedback me avise. Mais uma vez obrigado.
